-- YOUR CODE GOES HERE
-- CREATE YOUR DATABASE
-- CREATE YOUR TABLES
-- ADD RECORDS TO YOUR TABLE

DROP DATABASE IF EXISTS cows2;

CREATE DATABASE cows2;

USE cows2;

CREATE TABLE cowList (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name text, description text);